### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by kevinpainchaud**
- Upgrade Node from v16 to v20
- Upgrade actions/checkout and actions/setup-node from v3 to v4

### CODE REVIEW

**Comment by nwtgck** [comment]
Thanks!
I'll merge dependabot PRs for dependency updates.

**Comment by nwtgck** [comment]
I'd like to separate a commit for the engine update to Node.js 20. The engine update may include:
- actions/setup-node (node-version)
- Type definition `@types/node`
- `using` in action.yaml

**Comment by nwtgck** [comment]
`nwtgck/actions-netlify@v3.0` using node20 released now.

**Comment by kevinpainchaud** [comment]
Thanks! 🙏

**Pull request closed without merging**
