### PR TITLE
Add deploy message

### PR DESCRIPTION
**Pull request by South-Paw**
## Description

* Cleaned up some of the repo files while I was trying to debug #28 (wasn't successful in fixing it though 😞)
* Added `deploy-message` param to the action
  * Allows for a custom deploy message to be set when triggering a build in Netlify

### CODE REVIEW

**Comment by South-Paw** [comment]
@nwtgck it looks like I built and included the new dist with this PR sorry... 🤦‍♂

Would you like me to revert it before merging - I would also suggest building/testing/versioning it yourself before you merge 👍

Thanks for the great action :)

**Comment by nwtgck** [comment]
@South-Paw Thank you very much! Actually, I wanted the deploy message so much. I'd like to merge this feature.

But, I don't merge cleaning up repos things. So please keep the following files.
- lint related files
- `__tests__/main.test.ts` (one day I'd like to write a test)
- src/wait.ts  (not used but for __tests__/main.test.ts )
- jest.config.js
- tsconfig.json

**Comment by South-Paw** [comment]
@nwtgck I have re-added the test again and changed back the linting changes.

The tsconfig bits removed aren't relevant imo - you don't need the  `outDir` or `rootDir` as you are not building using `tsc` - you're building via `ncc`.

**Comment by South-Paw** [comment]
Also the `tsc` command fails because of #28

**Comment by nwtgck** [comment]
@South-Paw Thanks.

I'd like to keep pull requests small as possible. So, I don't want to include unrelated changes in single PR. Could you create another PR when you have different suggestion from deploy-message feature?

**Comment by South-Paw** [comment]
If there are any more changes you'd like made, please let me know - I'd like to have this merged/released so I can implement it in our Github workflows tomorrow

I'm trusting you'll test the deployment is working as intended? Because I don't know what Netlify site your CI deploys to 😄

**Comment by nwtgck** [comment]
@South-Paw I think only this commit https://github.com/nwtgck/actions-netlify/pull/39/commits/7144f56426c52a52d56711895e9f45b615f3534d is enough for me. 

> Because I don't know what Netlify site your CI deploys to 😄

Don't worry about it. I'll use this feature before merge.

**Pull request closed without merging**
