### PR TITLE
Readme: clarify how paths are looked up

### PR DESCRIPTION
**Pull request by rstacruz**
I found myself wondering where netlify-config-path is relative to (is it relative to publish-dir? the .github/workflows/ dir?). I hope this clarifies it a bit for future readers.

### CODE REVIEW

**Comment by nwtgck** [comment]
@rajington Thank you very much!

The behavior of `netlify-config-path` and `functions-dir` depend on <https://github.com/netlify/js-client/>. I'll check the implementation.

**Comment by rstacruz** [comment]
If I may suggest, I think it's perfectly fine the way it is... I can't think of a use case for relative paths (relative to what?). I might even suggest to drop `./` from the docs, like so:

```diff
-netlify-config-path: './netlify.toml'
+netlify-config-path: 'netlify.toml'

-publish-dir: './public'
+publish-dir: 'public'
```

This should make it a bit more obvious, and also look similar to netlify.toml configuration. I haven't tested it if it'll work though.

**Comment by nwtgck** [comment]
@rstacruz Thank you very much for suggestion.

I'm going to use `somePath` instead of `path.resolve(process.cwd(), somePath)`. Relative path should be relative to current working directory,  and absolute path should be also used if possible.

**Comment by nwtgck** [comment]
@rstacruz 

Here is the specification.

- When a path is a relative path, the path is relative to the project root by default and can be changed with `working-directory: ...` (https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses).

**Comment by nwtgck** [comment]
The relative paths are now relative to the project root, which is **the specification of GitHub Actions**. When you see the paths in github action yaml files even in .github/workflows, they are always relative to the project root except specifying `run` with `working-directory: ...`.

> All paths (eg, `publish-dir`, `netlify-config-path`, `functions-dir`) are relative to the project's root.

The message is very kind for users. My concern is that users might think only relative paths are available. But the facts is that the paths can be specified with absolute paths not only relative paths.

And I prefer to use `./mydir` for writing relative path because it is clear that the string is a path, not just string.

**Comment by nwtgck** [comment]
@rstacruz I'll use the sentence in the first commit of this PR like the following because it is very kind for users.

```md
All paths (eg, publish-dir, netlify-config-path, functions-dir) are relative to the project's root or absolute paths.
```

**Comment by nwtgck** [comment]
@rstacruz  I merged! GitHub UI shows the "merge icon", but merged.
https://github.com/nwtgck/actions-netlify/compare/8812f4f220b4d7bb21a6981748ddfb4c08dd1173...03adc49c9c8a39c5972475a3010f6cfcb745589d

**Pull request closed without merging**
