### PR TITLE
feat: Show old urls on pull-request

### LINKED ISSUE #384: Support for multiple deploys on the same PR?
the overwrite comment on PR uses a static lookup string. should it instead be based on the app id? This would allow to reuse the same comment with multiple deploys?

### PR DESCRIPTION
**Pull request by peaceiris**
This change allows a pull-request has a list of other deploy preview URLs, not only the latest one.

Tested on https://github.com/peaceiris/hugo-theme-iris/pull/306

https://user-images.githubusercontent.com/30958501/112139999-c956a500-8c16-11eb-906e-87fd6189d5f4.mov

### CODE REVIEW

**Comment by nwtgck** [comment]
Very interesting.

But, I thing this feature is realized by opening the old deploy preview URL in the CI checks below. That is easier to follow the specific commit with Git SHA1 and also its message.

https://user-images.githubusercontent.com/10933561/112226505-9097e980-8c71-11eb-9102-7da021947612.mp4

**Comment by peaceiris** [comment]
Thank you for your review, That sounds better. I will do so!

**Comment by peaceiris** [comment]
I just missed the response from the `enable-commit-status` option. Thanks.


https://user-images.githubusercontent.com/30958501/112251411-8809d800-8c9e-11eb-8048-3b07b049a535.mov

**Comment by polarathene** [comment]
> But, I thing this feature is realized by opening the old deploy preview URL in the CI checks below. That is easier to follow the specific commit with Git SHA1 and also its message.

This could be a nice feature, but once you use an alias it is no longer valid. Perhaps a better improvement (so that it can be used beyond the status check shown here), is to also include the deploy ID as an output. That enables using it for accessing prior build previews as well as linking to their build log pages.

As comment is not customizable, I use a separate action for managing the deploy comment, I could keep a `<details>` list this way (but using comment history makes sense to me when this is relevant). I use the alias for preview link, but if I wanted to link to the log as well I'd need that deploy ID value.

**Pull request closed without merging**
