### PR TITLE
feat: support branch deploy

### PR DESCRIPTION
**Pull request by rajington**
Updated deps, added docs and tests

See it working: https://github.com/rajington/actions-netlify/pull/1

### CODE REVIEW

**Comment by nwtgck** [comment]
@rajington Thank you so much! I'll modify a little and merge this.

**Comment by nwtgck** [comment]
I think name "branch" has wide meaning. The "branch" is a branch name of branch deploy. I'd like to name that can be descriptive for everyone. And, in the future, new concept related to ooo branch, might come. For that time, I'd like to name more descriptive name.

How about "branch-deploy-branch"?

**Comment by rajington** [comment]
that makes sense, whatever names you think is best are good with me, but thanks for checking!

**Comment by rajington** [comment]
it does change behavior a little bit too, people might not be expecting new commits to overwrite old previews, might need to accept "false" or something

**Comment by rajington** [comment]
also wasn't sure about the tsconfig ignore of `dist` but until I did that I kept getting type conflicts with node_modules

**Comment by nwtgck** [comment]
@rajington Thanks.
> also wasn't sure about the tsconfig ignore of dist but until I did that I kept getting type conflicts with node_modules

This problem: #28 ?

**Comment by rajington** [comment]
yeah that's it!

**Comment by rajington** [comment]
thinking more, `alias` might actually be the best name for it, bc it doesn't really have anything to do with branches at all (you could add in a random `foo` or `deploy-preview-23823` and it will work). and I think maybe if they don't provide an alias then it does current behavior, but they can easily apply an alias as the branch from their own workflow:

```yaml
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v...
        with:
          alias: ${{ github.head_ref }}
```

so no default (or logic) is required in the action

**Comment by rajington** [comment]
`alias` is what now.sh calls them

**Comment by rajington** [comment]
this way they could also use `alias: deploy-preview-${{ github.event.number }}` as well if they want to replicate that

**Comment by rajington** [comment]
simplifies things a bit and allows more flexibility IMO but cool with whatever

**Comment by nwtgck** [comment]
@rajington Very cool name!  I also know now.sh (Vercel) uses the word, alias.

However, my concern is that in the context of Netlify, that might not be called a prefix. `branch` proper is in the `deploy()` function is only for branch deployment, not for attaching prefix. For example, in the future, Netlify attaches the branch name, `my-super-feature` to the middle of preview URL like <https://54d8d911---my-super-feature---mysite.netlify.app>. So, I'd like to use Netlifiy words in the Netlify context.

**Comment by rajington** [comment]
updated to `deploy-branch`

**Comment by rajington** [comment]
oh thought you meant `deploy-branch` like `production-branch` not `branch-deploy-branch`, I can let you take over though this has what we need to continue

**Comment by nwtgck** [comment]
Thank you so much. I'm considering the name now and I don't have a conclusion yet.

 `production-branch`, which is already defined should exist and be a real Git branch. However, `deploy-branch` in this PR is not an actual Git branch and can be any string. When users see the name `deploy-branch`, they might think that will be the only branch for deployment. I wish Netlify used "prefix" officially...

**Comment by rajington** [comment]
i think `prefix` might demonstrate the flexibility, just undo the last commit if you wanna stick with that. could also do multiple inputs, but can iterate as well

**Comment by rajington** [comment]
seems like they're going with "alias!"

**Comment by dwilt** [comment]
Hey guys, we'd love to use this functionality. When will this be merged?

**Comment by rajington** [comment]
that's the great part of GitHub actions, you can use it now! that's what we're doing internally
```
      - name: Deploy App
        uses: rajington/actions-netlify@b235a18
```

**Comment by dwilt** [comment]
🚀  That is true! I didn't realize that! Will do this but obviously we'd like to be able to stay up to date by using the standard version when new updates get pushed in!

**Comment by rajington** [comment]
absolutely, usually smaller projects solo maintenance is hard. we actually made another update to add a functions directory: https://github.com/rajington/actions-netlify/tree/feature/add-functions

**Comment by nwtgck** [comment]
@rajington Thanks too much. Alias sounds good!

I'd like to add some prefix to `alias` (e.g. `preview-alias`). Netlify officially uses `Domain alias`.

image

[Custom domains | Netlify Docs](https://docs.netlify.com/domains-https/custom-domains/)

**Comment by nwtgck** [comment]
`deploy-preview` is a better name?
image
[Site deploys overview | Netlify Docs](https://docs.netlify.com/site-deploys/overview/#definitions)

**Comment by nwtgck** [comment]
> Hey guys, we'd love to use this functionality. When will this be merged?

Thanks! I'd like to merge this when then input name is decided.

**Comment by rajington** [comment]
The name [has since been switched by Netlify](https://github.com/netlify/cli/issues/275#issuecomment-639868623) to avoid confusion and the CI [has already been updated with a deprecation](https://github.com/netlify/cli/pull/943/files#diff-e9001bf37e31e33db8a717da3ac59a69R26).

**Comment by nwtgck** [comment]
@rajington This means Netlify officially uses "alias"! Very great.
https://github.com/netlify/cli/pull/943

I think this PR is ready to merge.

**Comment by nwtgck** [comment]
It works.
image
<https://github.com/nwtgck/actions-netlify/commit/e3c5f95c7accae5d50ccaca73f0f2458e1583e95>

**Comment by nwtgck** [comment]
`alias: ${{ github.head_ref }}` also works well!
image
https://github.com/nwtgck/actions-netlify/pull/187#issuecomment-643566602

**Comment by nwtgck** [comment]
@rajington Thank you so much for everything! I'll merge this.

**Pull request merged**
